from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name="home"),  
	path('india/', views.india, name="india"), 
	path('states/',views.states , name="states"), 
	path('states/westbengal/',views.westbengal , name="westbengal"),
	path('states/maharashtra/',views.maharashtra , name="maharashtra"),
	path('states/andhrapradesh/',views.andhrapradesh , name="andhrapradesh"),
	path('states/karnataka/',views.karnataka , name="karnataka"),
	path('states/tamilnadu/',views.tamilnadu , name="tamilnadu"),
	path('states/uttarpradesh/',views.uttarpradesh , name="uttarpradesh"),
	path('states/delhi/',views.delhi , name="delhi"),
	path('states/odisha/',views.odisha , name="odisha"),
	path('states/kerala/',views.kerala , name="kerala"),
	path('states/telangana/',views.telangana , name="telangana"),
	path('states/bihar/',views.bihar , name="bihar"),
	path('states/assam/',views.assam , name="assam"),
	path('states/rajasthan/',views.rajasthan , name="rajasthan"),
	path('states/gujarat/',views.gujarat , name="gujarat"),
	path('states/madhyapradesh/',views.madhyapradesh , name="madhyapradesh"),
	path('states/haryana/',views.haryana , name="haryana"),
	path('states/chhattisgarh/',views.chhattisgarh , name="chhattisgarh"),
	path('states/punjab/',views.punjab , name="punjab"),
	path('states/jharkhand/',views.jharkhand , name="jharkhand"),
	path('states/jammuandkashmir/',views.jammuandkashmir , name="jammuandkashmir"),
	path('states/uttarakhand/',views.uttarakhand , name="uttarakhand"),
	path('states/goa/',views.goa , name="goa"),
	path('states/puducherry/',views.puducherry , name="puducherry"),
	path('states/tripura/',views.tripura , name="tripura"),
	path('states/himachalpradesh/',views.himachalpradesh , name="himachalpradesh"),
	path('states/chandigarh/',views.chandigarh , name="chandigarh"),
	path('states/manipur/',views.manipur , name="manipur"),
	path('states/arunachalpradesh/',views.arunachalpradesh , name="arunachalpradesh"),
	path('states/meghalaya/',views.meghalaya , name="meghalaya"),
	path('states/nagaland/',views.nagaland , name="nagaland"),
	path('states/ladakh/',views.ladakh , name="ladakh"),
	path('states/andamanandnicobarislands/',views.andamanandnicobarislands , name="andamanandnicobarislands"),
	path('states/sikkim/',views.sikkim , name="sikkim"),
	path('states/mizoram/',views.mizoram , name="mizoram"),
	path('states/damananddiudadraandnagarhaveli/',views.damananddiudadraandnagarhaveli , name="damananddiudadraandnagarhaveli"),
	path('states/lakshadweep/',views.lakshadweep , name="lakshadweep"),
]

